FurryFunnies/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('author/', include('author.urls')),
    path('post/', include('post.urls')),
]

author/urls.py
from django.urls import path
from author import views

urlpatterns = [
    path('author/', views.AuthorCreateView.as_view(), name='author_create_page'),
    path('author/', views.AuthorDetailsView.as_view(), name='author_details_page'),
    path('author/', views.AuthorEditView.as_view(), name='author_edit_page'),
    path('author/', views.AuthorDeleteView.as_view, name='author_delete_page'),
]

common/urls.py
from django.urls import path

from .views import BasePage


urlpatterns = [
    path('', BasePage.as_view(), name='base'),
]

post/urls.py
from django.urls import path, include
from post import views

urlpatterns = [
    path('posts/', views.CreatePostView.as_view(), name='post_create_page'),
    path('posts/<int:post_id>/', include([
        path('edit/', views.DetailPostView.as_view(), name='post_edit_page'),
        path('details/', views.EditPostView.as_view(), name='post_details_page'),
        path('delete/', views.DeletePostView.as_view(), name='post_delete_page'),
    ]))
]

author/models.py
from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models

from .validators import validate_letters, validate_digits


# Create your models here.
class Author(models.Model):
    first_name = models.CharField(
        max_length=40,
        blank=False,
        validators=[MinLengthValidator(4), validate_letters],
    )

    last_name = models.CharField(
        max_length=50,
        blank=False,
        validators=[MinLengthValidator(2), validate_letters],
    )

    passcode = models.CharField(
        max_length=6,
        blank=False,
        validators=[validate_digits],
        # Help_text="Your passcode must be a combination of 6 digits",
    )

    pets_number = models.PositiveIntegerField(
        blank=False,
        validators=[MinValueValidator(0)]
    )

    info = models.TextField(
            blank=True
    )

    image_url = models.URLField(
        blank=True
    )

common/models.py
from django.db import models

# Create your models here.

post/models.py
from django.core.validators import MinLengthValidator
from django.db import models
# from FurryFunnies.author.models import Author
# from FurryFunnies.author.validators import validate_letters, validate_digits


# Create your models here.
class Post(models.Model):
    title = models.CharField(
        max_length=50,
        unique=True,
        blank=False,
        validators=[MinLengthValidator(5)],
        error_messages={
            'unique': "Oops! That title is already taken. How about something fresh and fun?",
        }
    )

    image_url = models.URLField(
        help_text="Share your funniest furry photo URL!",
        blank=False,
    )

    content = models.TextField(
        blank=False
    )
    updated_at = models.DateTimeField(
        auto_now=True,
        editable=False
    )

    author = models.ForeignKey(
        to='author.Author',
        on_delete=models.CASCADE,
        related_name="post",
    )

author/forms.py
from django import forms
from FurryFunnies.mixins import PlaceholderMixin, ReadOnlyMixin
from author.models import Author


class AuthorBaseForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"


class AuthorCreateForm(PlaceholderMixin, AuthorBaseForm):
    pass


class AuthorEditForm(PlaceholderMixin, AuthorBaseForm):
    pass


class AuthorDeleteForm(ReadOnlyMixin, AuthorBaseForm):
    pass

post/forms.py
from django import forms
from FurryFunnies.mixins import PlaceholderMixin, ReadOnlyMixin
from post.models import Post


class PostBaseForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ('author',)


class PostCreateForm(PlaceholderMixin, PostBaseForm):
    pass


class PostEditForm(PlaceholderMixin, PostBaseForm):
    pass


class PostDeleteForm(ReadOnlyMixin, PostBaseForm):
    pass

author/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from FurryFunnies.utils import get_user_obj
from author.forms import AuthorCreateForm, AuthorEditForm, AuthorDeleteForm
from author.models import Author


class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorCreateForm
    template_name = 'create-author.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.owner = get_user_obj()
        return super().form_valid(form)


class AuthorEditView(UpdateView):
    model = Author
    form_class = AuthorEditForm
    pk_url_kwarg = 'id'
    template_name = 'edit-author.html'
    success_url = reverse_lazy('base')


class AuthorDeleteView(DeleteView):
    model = Author
    form_class = AuthorDeleteForm
    pk_url_kwarg = 'id'
    template_name = 'delete-author.html'
    success_url = reverse_lazy('base')

    def get_initial(self):
        return self.object.__dict__

    def form_invalid(self, form):
        return self.form_valid(form)


class AuthorDetailsView(DetailView):
    model = Author
    pk_url_kwarg = 'id'
    template_name = 'author-author.html'

common/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import BaseFormView
from FurryFunnies.utils import get_user_obj
from author.forms import AuthorCreateForm
from post.models import Post


class BasePage(ListView, BaseFormView):
    model = Post
    form_class = AuthorCreateForm
    success_url = reverse_lazy('base')

    def get_template_names(self):
        author = get_user_obj()

        if author:
            return ['base-with-author.html']

        return ['base-no-author.html']

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

post/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, UpdateView, DetailView, DeleteView
from FurryFunnies.utils import get_user_obj
from post.forms import PostCreateForm, PostEditForm, PostDeleteForm
from post.models import Post
# Create your views here.


class CreatePostView(CreateView):
    model = Post
    form_class = PostCreateForm
    template_name = 'create-post.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.owner = get_user_obj()
        return super().form_valid(form)


class DetailPostView(DetailView):
    model = Post
    pk_url_kwarg = 'id'
    template_name = 'details-post.html'


class EditPostView(UpdateView):
    model = Post
    form_class = PostEditForm
    pk_url_kwarg = 'id'
    template_name = 'edit-post.html'
    success_url = reverse_lazy('home')


class DeletePostView(DeleteView):
    model = Post
    form_class = PostDeleteForm
    pk_url_kwarg = 'id'
    template_name = 'delete-post.html'
    success_url = reverse_lazy('home')

    def get_initial(self):
        return self.object.__dict__

    def form_invalid(self, form):
        return self.form_valid(form)

templates/base-no-author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base-with-author.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=\, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <title>FurryFunnies</title>
  </head>
  <body>
    <div id="wrapper">
      <header>
        <!-- Navigation -->

        <!-- Logo image: a link to index/home page -->
        <a id="logo" href="#">
          <img id="logo-img" src="{% static 'images/logo.png' %}" alt="logo" />
        </a>

        <nav>
          <!-- If there is an author's profile -->
          <div class="user">
            <a href="#">Dashboard</a>
            <a href="#">New Post</a>
            <a href="#">Author's Profile</a>
          </div>

          <!-- If author's profile has NOT been created -->
          <div class="guest">
            <a href="#">Create Author's Profile</a>
          </div>
        </nav>
      </header>


<!--      {% block content %}-->
      <!-- Your page content goes here -->
<!--      {% endblock %}-->
      

<!-- footer -->
    <footer>
      <p>&copy; 2024 FurryFunnies by SoftUni Team. All rights reserved.</p>
    </footer>
  </body>
</html>

templates/create-author.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=\, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/styles/styles.css" />
    <title>FurryFunnies</title>
  </head>
  <body>
    <div id="wrapper">
      <header>
        <!-- Navigation -->

        <!-- Logo image: a link to index/home page -->
        <a id="logo" href="#">
          <img id="logo-img" src="/static/images/logo.png" alt="logo" />
        </a>

        <nav>
          <!-- If there is an author's profile -->
          <div class="user">
            <a href="#">Dashboard</a>
            <a href="#">New Post</a>
            <a href="#">Author's Profile</a>
          </div>

          <!-- If author's profile has NOT been created -->
          <div class="guest">
            <a href="#">Create Author's Profile</a>
          </div>
        </nav>
      </header>

      <main>
        <!-- Create Author's Profile Form (Only if no author's profile has been created) -->
        <section id="register">
          <div class="form">
            <h2>Create Author's Profile</h2>

            <form class="register-form" method="" action="">
              <div>
                <label for="id_first_name">First Name:</label>

                <input
                  type="text"
                  name="first_name"
                  maxlength="40"
                  placeholder="Enter your first name..."
                  required
                  id="id_first_name"
                />
              </div>

              <div>
                <label for="id_last_name">Last Name:</label>

                <input
                  type="text"
                  name="last_name"
                  maxlength="50"
                  placeholder="Enter your last name..."
                  required
                  id="id_last_name"
                />
              </div>

              <div>
                <label for="id_passcode">Passcode:</label>

                <div class="helptext" id="id_passcode_helptext">
                  Your passcode must be a combination of 6 digits
                </div>

                <input
                  type="password"
                  name="passcode"
                  maxlength="6"
                  placeholder="Enter 6 digits..."
                  required
                  aria-describedby="id_passcode_helptext"
                  id="id_passcode"
                />
              </div>

              <div>
                <label for="id_pets_number">Pets Number:</label>

                <input
                  type="number"
                  name="pets_number"
                  min="0"
                  placeholder="Enter the number of your pets..."
                  required
                  id="id_pets_number"
                />
              </div>

              <!-- form button -->
              <button type="submit">Create</button>
            </form>
          </div>
        </section>
      </main>
    </div>

    <!-- footer -->
    <footer>
      <p>&copy; 2024 FurryFunnies by SoftUni Team. All rights reserved.</p>
    </footer>
  </body>
</html>

templates/create-post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=\, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/styles/styles.css" />
    <title>FurryFunnies</title>
  </head>
  <body>
    <div id="wrapper">
      <header>
        <!-- Navigation -->

        <!-- Logo image: a link to index/home page -->
        <a id="logo" href="#">
          <img id="logo-img" src="/static/images/logo.png" alt="logo" />
        </a>

        <nav>
          <!-- If there is an author's profile -->
          <div class="user">
            <a href="#">Dashboard</a>
            <a href="#">New Post</a>
            <a href="#">Author's Profile</a>
          </div>

          <!-- If author's profile has NOT been created -->
          <div class="guest">
            <a href="#">Create Author's Profile</a>
          </div>
        </nav>
      </header>

      <main>
        <!-- Add Post Form -->
        <section id="create">
          <div class="form">
            <h2>New Post</h2>

            <form class="create-form" action="" method="">
              <div>
                <label for="id_title">Title:</label>

                <input
                  type="text"
                  name="title"
                  maxlength="50"
                  placeholder="Put an attractive and unique title..."
                  required
                  id="id_title"
                />
              </div>

              <div>
                <label for="id_image_url">Post Image URL:</label>

                <div class="helptext" id="id_image_url_helptext">
                  Share your funniest furry photo URL!
                </div>

                <input
                  type="url"
                  name="image_url"
                  maxlength="200"
                  required
                  aria-describedby="id_image_url_helptext"
                  id="id_image_url"
                />
              </div>

              <div>
                <label for="id_content">Content:</label>

                <textarea
                  name="content"
                  cols="40"
                  rows="10"
                  placeholder="Share some interesting facts about your adorable pets..."
                  required
                  id="id_content"
                ></textarea>
              </div>

              <!-- form button -->
              <button type="submit">Publish</button>
            </form>
          </div>
        </section>
      </main>
    </div>

    <!-- footer -->
    <footer>
      <p>&copy; 2024 FurryFunnies by SoftUni Team. All rights reserved.</p>
    </footer>
  </body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=\, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/styles/styles.css" />
    <title>FurryFunnies</title>
  </head>
  <body>
    <div id="wrapper">
      <header>
        <!-- Navigation -->

        <!-- Logo image: a link to index/home page -->
        <a id="logo" href="#">
          <img id="logo-img" src="/static/images/logo.png" alt="logo" />
        </a>

        <nav>
          <!-- If there is an author's profile -->
          <div class="user">
            <a href="#">Dashboard</a>
            <a href="#">New Post</a>
            <a href="#">Author's Profile</a>
          </div>

          <!-- If author's profile has NOT been created -->
          <div class="guest">
            <a href="#">Create Author's Profile</a>
          </div>
        </nav>
      </header>

      <main>
        <!-- Dashboard page -->

        <!-- Display a heading if there are posts -->
        <h2>Published Posts</h2>

        <!-- Display a heading if there are NO posts -->
        <h2>No published posts yet.</h2>

        <section id="dashboard">
          <!-- Display a div with information about each post (if any) -->

          <!-- first post -->
          <div class="post">
            <!-- post image -->
            <img
              src="https://cdn.pixabay.com/photo/2017/03/26/00/56/rabbit-2174679_1280.jpg"
              alt="My cool fluffy rabbits img"
            />
            <!-- post title -->
            <h3 class="title">My cool fluffy rabbits</h3>
            <!-- post content -->
            <p class="description">Adorable!</p>
            <!-- post details button -->
            <a class="details-btn" href="#">See More</a>
          </div>

          <!-- second post -->
          <div class="post">
            <!-- post image -->
            <img
              src="https://cdn.pixabay.com/photo/2024/03/04/18/39/ai-generated-8612899_1280.jpg"
              alt="My brash cat! img"
            />
            <!-- post title -->
            <h3 class="title">My brash cat!</h3>
            <!-- post content -->
            <p class="description">My funny cat!</p>
            <!-- post details button -->
            <a class="details-btn" href="#">See More</a>
          </div>

          <!-- third post -->
          <div class="post">
            <!-- post image -->
            <img
              src="https://cdn.pixabay.com/photo/2024/04/05/19/04/ai-generated-8678034_1280.jpg"
              alt="My clever dog :) img"
            />
            <!-- post title -->
            <h3 class="title">My clever dog :)</h3>
            <!-- post content -->
            <p class="description">Einstein is the …</p>
            <!-- post details button -->
            <a class="details-btn" href="#">See More</a>
          </div>
        </section>
      </main>
    </div>

    <!-- footer -->
    <footer>
      <p>&copy; 2024 FurryFunnies by SoftUni Team. All rights reserved.</p>
    </footer>
  </body>
</html>

templates/delete-author.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=\, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/styles/styles.css" />
    <title>FurryFunnies</title>
  </head>
  <body>
    <div id="wrapper">
      <header>
        <!-- Navigation -->

        <!-- Logo image: a link to index/home page -->
        <a id="logo" href="#">
          <img id="logo-img" src="/static/images/logo.png" alt="logo" />
        </a>

        <nav>
          <!-- If there is an author's profile -->
          <div class="user">
            <a href="#">Dashboard</a>
            <a href="#">New Post</a>
            <a href="#">Author's Profile</a>
          </div>

          <!-- If author's profile has NOT been created -->
          <div class="guest">
            <a href="#">Create Author's Profile</a>
          </div>
        </nav>
      </header>

      <main>
        <section id="edit">
          <div class="form">
            <h1>You are about to delete your Author's Profile</h1>
            <!-- Delete Author's Profile Form -->

            <form id="delete" class="register-form" method="" action="">
              <!-- Confirm Button -->
              <button type="submit">Confirm</button>
            </form>
          </div>
          <!-- End Delete Form -->
        </section>
      </main>
    </div>

    <!-- footer -->
    <footer>
      <p>&copy; 2024 FurryFunnies by SoftUni Team. All rights reserved.</p>
    </footer>
  </body>
</html>

templates/delete-post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=\, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/styles/styles.css" />
    <title>FurryFunnies</title>
  </head>
  <body>
    <div id="wrapper">
      <header>
        <!-- Navigation -->

        <!-- Logo image: a link to index/home page -->
        <a id="logo" href="#">
          <img id="logo-img" src="/static/images/logo.png" alt="logo" />
        </a>

        <nav>
          <!-- If there is an author's profile -->
          <div class="user">
            <a href="#">Dashboard</a>
            <a href="#">New Post</a>
            <a href="#">Author's Profile</a>
          </div>

          <!-- If author's profile has NOT been created -->
          <div class="guest">
            <a href="#">Create Author's Profile</a>
          </div>
        </nav>
      </header>

      <main>
        <!-- Delete Post Form -->
        <section id="edit">
          <div class="form">
            <h2>Delete Post</h2>

            <form class="edit-form" method="" action="">
              <div>
                <label for="id_title">Title:</label>

                <input
                  type="text"
                  name="title"
                  value="My clever dog :)"
                  maxlength="50"
                  readonly="readonly"
                  required
                  id="id_title"
                />
              </div>

              <div>
                <label for="id_image_url">Post Image URL:</label>

                <input
                  type="url"
                  name="image_url"
                  value="https://cdn.pixabay.com/photo/2024/04/05/19/04/ai-generated-8678034_1280.jpg"
                  maxlength="200"
                  readonly="readonly"
                  required
                  id="id_image_url"
                />
              </div>

              <div>
                <label for="id_content">Content:</label>

                <textarea
                  name="content"
                  cols="40"
                  rows="10"
                  readonly="readonly"
                  required
                  id="id_content"
                >
Einstein is the smartest dog ever!!!</textarea
                >
              </div>

              <!-- form button -->
              <button type="submit">Delete</button>
            </form>
          </div>
        </section>
      </main>
    </div>

    <!-- footer -->
    <footer>
      <p>&copy; 2024 FurryFunnies by SoftUni Team. All rights reserved.</p>
    </footer>
  </body>
</html>

templates/details-author.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=\, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/styles/styles.css" />
    <title>FurryFunnies</title>
  </head>
  <body>
    <div id="wrapper">
      <header>
        <!-- Navigation -->

        <!-- Logo image: a link to index/home page -->
        <a id="logo" href="#">
          <img id="logo-img" src="/static/images/logo.png" alt="logo" />
        </a>

        <nav>
          <!-- If there is an author's profile -->
          <div class="user">
            <a href="#">Dashboard</a>
            <a href="#">New Post</a>
            <a href="#">Author's Profile</a>
          </div>

          <!-- If author's profile has NOT been created -->
          <div class="guest">
            <a href="#">Create Author's Profile</a>
          </div>
        </nav>
      </header>

      <main>
        <!-- Author's Profile Details Section -->

        <section id="details">
          <div id="details-wrapper">
            <h2>Author's Profile Details</h2>

            <!-- if the author has provided a profile image link -->

            <img
              id="details-img"
              src="https://cdn.pixabay.com/photo/2016/03/31/19/56/avatar-1295395_1280.png"
              alt="profile img"
            />

            <!-- if the author has NO profile image link -->
            <img
              id="details-img"
              src="/static/images/default.png"
              alt="profile img"
            />

            <!-- author's full name -->
            <p id="details-title">Test User</p>

            <!-- number of posts -->
            <p id="nutrition">Published Posts: 3</p>

            <div id="info-wrapper">
              <div id="details-description">
                <!-- pets number -->
                <p>Pets Number: 4</p>

                <!-- info if provided, otherwise skip the line -->
                <p>Some funny info of me and all my pets</p>

                <!-- Latest activity -->
                <p>-------------------------------</p>
                <!-- latest activity if there are posts: display the title of the last updated post -->
                <p>
                  Last Updated Post:
                  <strong>My cool fluffy rabbits</strong>
                </p>

                <!-- latest activity if there are NO posts -->
                <p>
                  Last Updated Post:
                  <strong>N/A</strong>
                </p>
              </div>

              <!--Edit and Delete buttons -->
              <div id="action-buttons">
                <a href="#" id="edit-btn">Edit</a>
                <a href="#" id="delete-btn">Delete</a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>

    <!-- footer -->
    <footer>
      <p>&copy; 2024 FurryFunnies by SoftUni Team. All rights reserved.</p>
    </footer>
  </body>
</html>

templates/edit-author.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=\, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/styles/styles.css" />
    <title>FurryFunnies</title>
  </head>
  <body>
    <div id="wrapper">
      <header>
        <!-- Navigation -->

        <!-- Logo image: a link to index/home page -->
        <a id="logo" href="#">
          <img id="logo-img" src="/static/images/logo.png" alt="logo" />
        </a>

        <nav>
          <!-- If there is an author's profile -->
          <div class="user">
            <a href="#">Dashboard</a>
            <a href="#">New Post</a>
            <a href="#">Author's Profile</a>
          </div>

          <!-- If author's profile has NOT been created -->
          <div class="guest">
            <a href="#">Create Author's Profile</a>
          </div>
        </nav>
      </header>

      <main>
        <!-- Edit Author's Profile Form -->

        <section id="register">
          <div class="form">
            <h2>Edit Author's Profile</h2>

            <form class="register-form" method="" action="">
              <div>
                <label for="id_first_name">First Name:</label>

                <input
                  type="text"
                  name="first_name"
                  value="Test"
                  maxlength="40"
                  required
                  id="id_first_name"
                />
              </div>

              <div>
                <label for="id_last_name">Last Name:</label>

                <input
                  type="text"
                  name="last_name"
                  value="User"
                  maxlength="50"
                  required
                  id="id_last_name"
                />
              </div>

              <div>
                <label for="id_pets_number">Pets Number:</label>

                <input
                  type="number"
                  name="pets_number"
                  value="4"
                  min="0"
                  required
                  id="id_pets_number"
                />
              </div>

              <div>
                <label for="id_info">Info:</label>

                <textarea name="info" cols="40" rows="10" id="id_info">
Some funny info of me and all my pets</textarea
                >
              </div>

              <div>
                <label for="id_image_url">Profile Image URL:</label>

                <input
                  type="url"
                  name="image_url"
                  value="https://cdn.pixabay.com/photo/2016/03/31/19/56/avatar-1295395_1280.png"
                  maxlength="200"
                  id="id_image_url"
                />
              </div>
              <!-- form button -->
              <button type="submit">Edit</button>
            </form>
          </div>
        </section>
      </main>
    </div>

    <!-- footer -->
    <footer>
      <p>&copy; 2024 FurryFunnies by SoftUni Team. All rights reserved.</p>
    </footer>
  </body>
</html>

templates/edit-post.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=\, initial-scale=1.0" />
    <link rel="stylesheet" href="/static/styles/styles.css" />
    <title>FurryFunnies</title>
  </head>
  <body>
    <div id="wrapper">
      <header>
        <!-- Navigation -->

        <!-- Logo image: a link to index/home page -->
        <a id="logo" href="#">
          <img id="logo-img" src="/static/images/logo.png" alt="logo" />
        </a>

        <nav>
          <!-- If there is an author's profile -->
          <div class="user">
            <a href="#">Dashboard</a>
            <a href="#">New Post</a>
            <a href="#">Author's Profile</a>
          </div>

          <!-- If author's profile has NOT been created -->
          <div class="guest">
            <a href="#">Create Author's Profile</a>
          </div>
        </nav>
      </header>

      <main>
        <!-- Edit Post Form -->
        <section id="edit">
          <div class="form">
            <h2>Edit Post</h2>

            <form class="edit-form" method="" action="">
              <div>
                <label for="id_title">Title:</label>

                <input
                  type="text"
                  name="title"
                  value="My clever dog :)"
                  maxlength="50"
                  required
                  id="id_title"
                />
              </div>

              <div>
                <label for="id_image_url">Post Image URL:</label>

                <input
                  type="url"
                  name="image_url"
                  value="https://cdn.pixabay.com/photo/2024/04/05/19/04/ai-generated-8678034_1280.jpg"
                  maxlength="200"
                  required
                  id="id_image_url"
                />
              </div>

              <div>
                <label for="id_content">Content:</label>

                <textarea
                  name="content"
                  cols="40"
                  rows="10"
                  required
                  id="id_content"
                >
Einstein is the smartest dog ever!!!</textarea
                >
              </div>

              <!-- form button -->
              <button type="submit">Edit</button>
            </form>
          </div>
        </section>
      </main>
    </div>

    <!-- footer -->
    <footer>
      <p>&copy; 2024 FurryFunnies by SoftUni Team. All rights reserved.</p>
    </footer>
  </body>
</html>